# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SENE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SENE
  pod 'GRKOpenSSLFramework'
end

target 'SoftEther' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoftEther

end
