# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cedar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cedar

end

target 'Mayaqua' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mayaqua
  pod 'GRKOpenSSLFramework'
end

target 'SoftEtherVPN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoftEtherVPN

end

target 'Mayaqua_macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenSSL-Universal', :git => 'https://github.com/krzyzanowskim/OpenSSL.git', :branch => :master
end
